export class EventError extends Error {
  constructor(public code: string, message: string) {
    super(message);
    this.name = 'EventError';
  }
}

export const ERROR_CODES = {
  NOT_FOUND: 'EVENT_NOT_FOUND',
  NOT_PUBLISHED: 'EVENT_NOT_PUBLISHED',
  ALREADY_CANCELLED: 'EVENT_ALREADY_CANCELLED',
  AT_CAPACITY: 'EVENT_AT_CAPACITY',
  DEADLINE_PASSED: 'REGISTRATION_DEADLINE_PASSED',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
  NOT_FACE_VERIFIED: 'USER_NOT_FACE_VERIFIED',
  NOT_VERIFIED: 'USER_NOT_VERIFIED',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  PAYMENT_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  PROMO_INVALID: 'PROMO_CODE_INVALID',
  PROMO_EXPIRED: 'PROMO_CODE_EXPIRED',
  PROMO_EXHAUSTED: 'PROMO_CODE_EXHAUSTED',
  ALREADY_CHECKED_IN: 'ALREADY_CHECKED_IN',
  REVIEW_NOT_ELIGIBLE: 'REVIEW_NOT_ELIGIBLE',
  DUPLICATE_REVIEW: 'DUPLICATE_REVIEW',
  UNAUTHORIZED: 'UNAUTHORIZED',
  ADMIN_REVIEW_REQUIRED: 'ADMIN_REVIEW_REQUIRED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};
