export enum MarketplaceErrorCode {
  UNAUTHORIZED_ACTION = 'MARKETPLACE_UNAUTHORIZED_ACTION',
  COMPANY_NOT_VERIFIED = 'MARKETPLACE_COMPANY_NOT_VERIFIED',
  PROFILE_NOT_FOUND = 'MARKETPLACE_PROFILE_NOT_FOUND',
  REQUIREMENT_NOT_FOUND = 'MARKETPLACE_REQUIREMENT_NOT_FOUND',
  PROPOSAL_NOT_FOUND = 'MARKETPLACE_PROPOSAL_NOT_FOUND',
  CONTRACT_NOT_FOUND = 'MARKETPLACE_CONTRACT_NOT_FOUND',
  MILESTONE_NOT_FOUND = 'MARKETPLACE_MILESTONE_NOT_FOUND',
  INVALID_TRANSITION = 'MARKETPLACE_INVALID_TRANSITION',
  ALREADY_EXISTS = 'MARKETPLACE_ALREADY_EXISTS',
}

export class MarketplaceError extends Error {
  constructor(
    public code: MarketplaceErrorCode,
    public message: string,
    public statusCode: number = 400
  ) {
    super(message);
    this.name = 'MarketplaceError';
  }
}
